#!/usr/bin/env python3
print("Content-Type: text/html")
print()
print("<html>")
print("<head><title>Python CGI Test</title></head>")
print("<body>")
print("<h1>Hello from Python CGI!</h1>")
print("<p>This is a test CGI script running with Python.</p>")
print("</body>")
print("</html>")
