import time

print("Content-Type: text/html\r\n\r\n")
time.sleep(0.5)
print("<html>")
time.sleep(0.5)
print("<head><title>Python CGI Test</title></head>")
time.sleep(0.5)
print("<body>")
time.sleep(0.5)
print("<h1>Hello from Python CGI!</h1>")
time.sleep(0.5)
print("<p>This is a test CGI script running with Python.</p>")
time.sleep(0.5)
print("</body>")
time.sleep(0.5)
print("</html>")
